# Generated by Django 3.1.7 on 2021-04-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OvinoSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acessa',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
