# Generated by Django 3.1.7 on 2021-04-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('cod', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('quant', models.IntegerField()),
            ],
            options={
                'verbose_name': 'insumo',
                'verbose_name_plural': 'insumos',
            },
        ),
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('especie', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('producao', models.IntegerField()),
                ('doacao', models.IntegerField()),
                ('venda', models.IntegerField()),
                ('extravio', models.IntegerField()),
                ('ifrn', models.IntegerField()),
            ],
            options={
                'verbose_name': 'planta',
                'verbose_name_plural': 'plantas',
            },
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('cod', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField(max_length=30)),
                ('visitante', models.TextField()),
            ],
            options={
                'verbose_name': 'visita',
                'verbose_name_plural': 'visitas',
            },
        ),
    ]
