# Generated by Django 3.1.7 on 2021-02-20 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nome', models.CharField(max_length=30)),
                ('raca', models.CharField(default='Bovino', max_length=30)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('termino', models.DateField(blank=True, null=True)),
                ('femea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='femea', to='BovSystem.animal')),
                ('macho', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='macho', to='BovSystem.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('tipo', models.CharField(choices=[('med', 'Medicamento'), ('equip', 'Equipamento Veterinário'), ('limp', 'Material de Limpeza')], max_length=30)),
                ('nome', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('validade', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Financeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, default='')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Secacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('leite', models.CharField(choices=[('NÃO MAIS', 'NÃO MAIS'), ('POUCO LEITE', 'POUCO LEITE'), ('MUITO LEITE', 'MUITO LEITE')], max_length=30)),
                ('ativa', models.BooleanField(default=True)),
                ('termino', models.DateField(blank=True, null=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BovSystem.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Saida_Leite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('destino', models.CharField(max_length=30)),
                ('responsavel', models.CharField(max_length=30)),
                ('ganho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BovSystem.registro_financeiro')),
            ],
        ),
        migrations.CreateModel(
            name='Produc_leite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('femea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BovSystem.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Nascimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('peso_nasc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('filhote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BovSystem.animal')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matriz', to='BovSystem.animal')),
                ('pai', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pai', to='BovSystem.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Gravidez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('termino', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BovSystem.animal')),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BovSystem.cobertura')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada_Saida_Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saida')], max_length=10)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('quantidade', models.IntegerField()),
                ('gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BovSystem.registro_financeiro')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BovSystem.material')),
            ],
        ),
        migrations.CreateModel(
            name='Acessa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.CharField(choices=[('adm', 'Administrador'), ('cord', 'Cordenador'), ('bols', 'Bolsista'), ('vist', 'Visitante')], max_length=15)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BovSystem.setor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BovSystem.usuario')),
            ],
        ),
    ]
