# Generated by Django 3.1.7 on 2021-02-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BovSystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrada_Saida_Estoque',
        ),
    ]
