# Generated by Django 3.1.7 on 2021-02-28 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BovSystem', '0002_auto_20210228_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('Medicamento', 'Medicamento'), ('Equipamento Veterinário', 'Equipamento Veterinário'), ('Material de Limpeza', 'Material de Limpeza')], max_length=30),
        ),
        migrations.CreateModel(
            name='Entrada_Saida_Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saida')], max_length=10)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('quantidade', models.IntegerField()),
                ('gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BovSystem.registro_financeiro')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BovSystem.material')),
            ],
        ),
    ]
