# Generated by Django 3.1.7 on 2021-03-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BovSystem', '0003_auto_20210228_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobertura',
            name='inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gravidez',
            name='inicio',
            field=models.DateField(),
        ),
    ]
