# Generated by Django 3.1.7 on 2021-03-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BovSystem', '0004_auto_20210301_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessa',
            name='permissao',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Cordenador', 'Cordenador'), ('Bolsista', 'Bolsista'), ('Visitante', 'Visitante')], max_length=15),
        ),
    ]
