# Generated by Django 3.1.7 on 2021-03-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BovSystem', '0005_auto_20210327_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessa',
            name='setor',
            field=models.CharField(choices=[('Bovinocultura', 'Bovinocultura'), ('Viveiro', 'Viveiro'), ('Ovinocultura', 'Ovinocultura')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
