# Generated by Django 3.1.7 on 2021-04-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BovSystem', '0007_auto_20210327_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acessa',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
